#pragma once
#include <Windows.h>
#include "Include/Image.h"
#include "Include/Plant.h"
#define DDIMG Sexy::DDImage*
#define ENABLE_CONSOLE TRUE

DWORD DISPOSABLE;
CONST VOID* DRAW_BACKDROP_HOOK = (CONST VOID*)0x41ACF0;
CONST VOID* DRAW_BACKDROP_JBK = (CONST VOID*)0x41ACF6;
CONST VOID* BOARD_MDOWN_HOOK = (CONST VOID*)0x411F20;
CONST VOID* BOARD_MDOWN_JBK = (CONST VOID*)0x411F26;
CONST VOID* BOARD_MUP_HOOK = (CONST VOID*)0x412540;
CONST VOID* BOARD_MUP_JBK = (CONST VOID*)0x412545;
CONST VOID* UPDATE_HOOK = (CONST VOID*)0x415920;
CONST VOID* UPDATE_JBK = (CONST VOID*)0x41592C;
CONST VOID* LOAD_HOOK = (CONST VOID*)0x452CB2;
CONST VOID* LOAD_JBK = (CONST VOID*)0x452CB7;
CONST VOID* DRAW_IMG = (CONST VOID*)0x587270;
CONST CHAR* BADAPPLE_DIR = "BadApple/";
CONST CHAR* IMAGE_SEQUENCE = "BadApple/Sequence/";
CONST CHAR* IMAGE_PREFIX = "bad_apple_";
CONST CHAR* IMAGE_PPR = "BadApple/Sequence/bad_apple_";
CONST CHAR* BG_DIR = "BadApple/AlteredBG/";
CONST CHAR* COMPRESSED_DIR = "BadApple/Compressed";
CONST CHAR* IMAGE_EXT = ".jpg";

CONST DOUBLE FPS = 29.99;
CONST UINT32 FRAME_SKIP = 1;
CONST UINT32 FRAME_COUNT = 6562;
CONST UINT32 FRAME_WIDTH = 800;
CONST UINT32 FRAME_HEIGHT = 600;
CONST UINT32 FRAME_SIZE = FRAME_WIDTH * FRAME_HEIGHT;

// Data
BYTE* CURR_FRAME_DATA;
BYTE* COMPRESSED_DATA;

// Backgrounds
UINT BGDICT[8];
DDIMG IDICT[8];
DDIMG DICT[8];
DDIMG SAMPL;
DDIMG LAWND;
DDIMG LAWNN;
DDIMG POOLD;
DDIMG POOLN;
DDIMG ROOFD;
DDIMG ROOFN;
DDIMG ZEND;
DDIMG ZENN;

CONST SeedType MAX_SEED_CONVERT = SEED_MELONPULT;
CONST SeedType SEED_CONVERT[] = {
	SEED_PUFFSHROOM,// Peashooter
	SEED_SUNSHROOM,// Sunflower
	SEED_DOOMSHROOM,// Cherry Bomb
	SEED_WALLNUT, // Wallnut
	SEED_HYPNOSHROOM,// Potato Mine
	SEED_ICESHROOM,// Snow Pea
	SEED_SCAREDYSHROOM,// Chomper
	SEED_FUMESHROOM,// Repeater
	SEED_PEASHOOTER,// Puff-shroom
	SEED_SUNFLOWER,// Sunshroom
	SEED_REPEATER,// Fumeshroom
	SEED_GRAVEBUSTER,// Gravebuster
	SEED_POTATOMINE,// Hypnoshroom
	SEED_CHOMPER,// Scaredyshroom
	SEED_SNOWPEA,// IceShroom
	SEED_CHERRYBOMB,// DoomShroom
	SEED_LILYPAD,// Lilypad
	SEED_SQUASH,// Squash
	SEED_STARFRUIT,// Threepeater
	SEED_SEASHROOM,// Tanglekelp
	SEED_BLOVER,// Jalapeno
	SEED_MAGNETSHROOM,// SpikeWeed
	SEED_PLANTERN,// Torchwood
	SEED_PUMPKIN,//Tallnut
	SEED_TANGLEKELP,// Seashroom
	SEED_TORCHWOOD,// Plantern
	SEED_CACTUS,// Cactus
	SEED_SPLITPEA,// Splitpea
	SEED_THREEPEATER,// Starfruit
	SEED_TALLNUT,// Pumpkin
	SEED_SPIKEWEED,// Magnetshroom
	SEED_KERNELPULT,// Cabbagepult
	SEED_FLOWERPOT,// Flowerpot
	SEED_CABBAGEPULT,// Kernel Pult
	SEED_INSTANT_COFFEE,// Coffee Bean
	SEED_MARIGOLD,// Garlic
	SEED_UMBRELLA,// Umbrella
	SEED_GARLIC,// Marigold
	SEED_MELONPULT// Melon
};