#pragma once
#include <Windows.h>
#include "Include/Image.h"
#define DDIMG Sexy::DDImage*
#define ENABLE_CONSOLE TRUE

DWORD DISPOSABLE;
CONST VOID* DRAW_BACKDROP_HOOK = (CONST VOID*)0x416527;
CONST VOID* DRAW_BACKDROP_JBK = (CONST VOID*)0x41652D;
CONST VOID* LOAD_HOOK = (CONST VOID*)0x452CB2;
CONST VOID* DRAW_IMG = (CONST VOID*)0x587270;
CONST CHAR* BADAPPLE_DIR = "BadApple/";
CONST CHAR* IMAGE_SEQUENCE = "BadApple/Sequence/";
CONST CHAR* IMAGE_PREFIX = "bad_apple_";
CONST CHAR* IMAGE_PPR = "BadApple/Sequence/bad_apple_";
CONST CHAR* BG_DIR = "BadApple/AlteredBG/";
CONST CHAR* COMPRESSED_DIR = "BadApple/Compressed";
CONST CHAR* IMAGE_EXT = ".jpg";

CONST DOUBLE FPS = 29.99;
CONST UINT32 FRAME_SKIP = 1;
CONST UINT32 FRAME_COUNT = 6562;
CONST UINT32 FRAME_WIDTH = 800;
CONST UINT32 FRAME_HEIGHT = 600;
CONST UINT32 FRAME_SIZE = FRAME_WIDTH * FRAME_HEIGHT;

// Backgrounds
DDIMG IDICT[8];
DDIMG DICT[8];
DDIMG SAMPL;
DDIMG LAWND;
DDIMG LAWNN;
DDIMG POOLD;
DDIMG POOLN;
DDIMG ROOFD;
DDIMG ROOFN;
DDIMG ZEND;
DDIMG ZENN;